spring.application.name=bunch
server.port=8080

# DB
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# LIQUIBASE
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=public

# LOGGING
logging.level.liquibase=debug
logging.level.org.springframework=info

# 5 minutes
jwt.access-token-expiration-ms=300000
# 7 days
jwt.refresh-token-expiration-ms=604800000

# JWT RSA keys (Resources)
jwt.private-key=${AUTH_PRIVATE_KEY_PATH:classpath:certs/private.pem}
jwt.public-key=${AUTH_PUBLIC_KEY_PATH:classpath:certs/public.pem}
